services:
  postgres:
    image: postgres:17
    container_name: goldentak_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: goldentak_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: goldentak_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: goldentak_app
    restart: always
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/goldentak_db?schema=public
      - DIRECT_URL=postgresql://postgres:123456@postgres:5432/goldentak_db?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_key_here
      - RACING_API_KEY=i89tdOwRYpbeFapUiduvyQ1C
      - RACING_API_SECRET=SftrRFyNKbvugc7XcY0mCmxM
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
