allowBuilds:
  '@firebase/util': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
onlyBuiltDependencies:
  - '@firebase/util'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
