// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl =
  process.env.DATABASE_URL ||
  "postgresql://postgres:123456@postgres:5432/goldentak_db?schema=public";
const directUrl =
  process.env.DIRECT_URL ||
  process.env.DATABASE_URL ||
  "postgresql://postgres:123456@postgres:5432/goldentak_db?schema=public";

export default defineConfig({
  schema: "prisma/schema",
  seed: {
    program: "tsx prisma/seed.ts",
  },
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
    directUrl: directUrl,
  },
});
